var booksOfTheBible=
[{Number: 1,Book: "Genesis"},
{Number: 2,Book: "Exodus"},
{Number: 3,Book: "Leviticus"},
{Number: 4,Book: "Numbers"},
{Number: 5,Book: "Deuteronomy"},
{Number: 6,Book: "Joshua"},
{Number: 7,Book: "Judges"},
{Number: 8,Book: "Ruth"},
{Number: 9,Book: "1 Samuel"},
{Number: 10,Book: "2 Samuel"	 },
{Number: 11,Book: "1 Kings"	 },
{Number: 12,Book: "2 Kings"	 },
{Number: 13,Book: "1 Chronicles"},
{Number: 14,Book: "2 Chronicles"} ,
{Number: 15,Book: "Ezra"} ,
{Number: 16,Book: "Nehemiah"},
{Number: 17,Book: "Esther"} ,
{Number: 18,Book: "Job"} ,
{Number: 19,Book: "Psalms"} ,
{Number: 20,Book: "Proverbs"} ,
{Number: 21,Book: "Ecclesiastes"} ,
{Number: 22,Book: "Song of Songs"} ,
{Number: 23,Book: "Isaiah"} ,
{Number: 24,Book: "Jeremiah"} ,
{Number: 25,Book: "Lamentations"} ,
{Number: 26,Book: "Ezekiel"} ,
{Number: 27,Book: "Daniel"} ,
{Number: 28,Book: "Hosea"} ,
{Number: 29,Book: "Joel"} ,
{Number: 30,Book: "Amos"} ,
{Number: 31,Book: "Obadiah"} ,
{Number: 32,Book: "Jonah"} ,
{Number: 33,Book: "Micah"} ,
{Number: 34,Book: "Nahum"} ,
{Number: 35,Book: "Habakkuk"} ,
{Number: 36,Book: "Zephaniah"} ,
{Number: 37,Book: "Haggai"} ,
{Number: 38,Book: "Zechariah"} ,
{Number: 39,Book: "Malachi "} ,
{Number: 40,Book: "Matthew"} ,
{Number: 41,Book: "Mark"} ,
{Number: 42,Book: "Luke"} ,
{Number: 43,Book: "John"} ,
{Number: 44,Book: "Acts"} ,
{Number: 45,Book: "Romans"} ,
{Number: 46,Book: "1 Corinthians" } ,
{Number: 47,Book: "2 Corinthians" } ,
{Number: 48,Book: "Galatians" 	} ,
{Number: 49,Book: "Ephesians" 	} ,
{Number: 50,Book: "Philippians"} ,
{Number: 51,Book: "Colossians"} ,
{Number: 52,Book: "1 Thessalonians"},
{Number: 53,Book: "2 Thessalonians"},
{Number: 54,Book: "1 Timothy" },
{Number: 55,Book: "2 Timothy" },
{Number: 56,Book: "Titus" 	},
{Number: 57,Book: "Philemon"	},
{Number: 58,Book: "Hebrews" 	},
{Number: 59,Book: "James" 	},
{Number: 60,Book: "1 Peter"},
{Number: 61,Book: "2 Peter"},
{Number: 62,Book: "1 John" 	},
{Number: 63,Book: "2 John" 	},
{Number: 64,Book: "3 John" 	},
{Number: 65,Book: "Jude"},
{Number: 66,Book: "Revelation"}
]; 